### ISSUE TITLE
Data annotation of Ho3D v2 dataset

### ISSUE THREAD

**Issue by M-leng** [hxwork/HandBooster_Pytorch#1]
Dear Hao Xu,

I have read your work on CVPR2023 and this work on CVPR2024. 

I have one question of the data annotation of Ho3d v2 dataset.

In your work on cvpr2023,  you noted that you used the pre-processed ground truths from handoccnet for ho3d dataset.

Did you also use the annotation of handoccnet on your new handbooster?

Looking forward for your reply.

Best wishes,
Zhiying

**Comment by hxwork** [comment]
Hi Zhiying,

Thanks for your interest. Yes, we use the pre-processed ground truths from HandOccNet to train both the diffusion model in our HandBooster and the reconstruction baselines.

**Comment by YiJian666** [comment]
> 嗨，Zhiying，
> 
> 感谢您的关注。是的，我们使用 HandOccNet 中经过预处理的基本事实来训练 HandBooster 中的扩散模型和重建基线。

[您好，我发现您曾经在HandOccNet下回复没有复现出论文结果，请问你最后是怎么解决的呢，希望您可以帮我解惑，不胜感激]
![Uploading 32962FE43E26CD6DAEB8E7CC4E88D912.jpg…]()

**Comment by YiJian666** [comment]
> Hi Zhiying,
> 
> Thanks for your interest. Yes, we use the pre-processed ground truths from HandOccNet to train both the diffusion model in our HandBooster and the reconstruction baselines.

您好，我发现您曾经在HandOccNet下回复没有复现出论文结果，请问你最后是怎么解决的呢，希望您可以帮我解惑，不胜感激
[32962FE43E26CD6DAEB8E7CC4E88D912](https://github.com/user-attachments/assets/36c4aac7-f2fa-4c42-a48e-2c3f6dfcdba0)
