### ISSUE TITLE
结果

### ISSUE THREAD

**Issue by YiJian666** [hxwork/HandBooster_Pytorch#3]
你好，请问您最后是怎么解决HandOCC项目下你没有复现出的结果的，我发现这个问题与您项目息息相关，我也想依次进行改进，可结果和您当初一样，不知道您是是否能帮助我解决疑惑？不胜感激
![32962fe43e26cd6daeb8e7cc4e88d912](https://github.com/user-attachments/assets/cdfda100-72c5-48ee-99ae-bf4578587b73)

**Comment by hxwork** [comment]
你好，

我们直接使用了HandOccNet论文中展示的结果。有关HandOccNet复现的问题请直接在HandOccNet的Issue下进行询问。
