### ISSUE TITLE
3D PCK data

### ISSUE THREAD

**Issue by zhoujun-7** [hxwork/HandBooster_Pytorch#4]
Hi Hao,

Thanks for your interesting work.
Could you please tell me how do you get the 3D PCK data of HO3D v2 and DexYCB for each method?

Looking forward to your reply.

Best Regard,
Jun

**Comment by hxwork** [comment]
Hi Jun,

We obtained the results either from their papers, produced by ourselves using their official codes, or released on the official server (e.g., for HO3D v2). Some results may have already disappeared due to the website update of CodaLab. Hope this can help you.
